"""Spatial Diagnostic Maps for Candidate Scouting Zones.

Renders publication-ready cartographic maps of candidate scouting priority polygons
with case-specific styling, area annotations, and explicit coarse-resolution context notes.
"""

from __future__ import annotations

from pathlib import Path
from typing import Any, Dict, List, Optional, Sequence, Tuple, Union

import matplotlib
matplotlib.use("Agg")
import matplotlib.patches as mpatches
import matplotlib.pyplot as plt
import numpy as np
from shapely.geometry import shape as shapely_shape


CASE_COLORS = {
    "NORMAL": "#2b83ba",
    "CASE_A": "#d7191c",
    "CASE_B": "#fdae61",
    "CASE_C": "#abd9e9",
    "CASE_D": "#e66101",
    "MULTI_SIGNAL": "#7b3294",
    "INSUFFICIENT_EVIDENCE": "#cccccc",
}


def plot_spatial_diagnostic_map(
    geojson_data: Dict[str, Any],
    bin_date: Union[str, pd.Timestamp],
    bin_index: int,
    aoi_bbox: Sequence[float],
    grid_bbox: Optional[Sequence[float]] = None,
    aoi_name: str = "Moiben-Soy Agricultural Pilot Zone",
    output_path: Optional[Union[str, Path]] = None,
    figsize: Tuple[int, int] = (9, 8),
    dpi: int = 300,
) -> plt.Figure:
    """Render a geospatial diagnostic map of candidate scouting zones for a specific canonical bin.

    Parameters
    ----------
    geojson_data : dict
        RFC 7946 GeoJSON FeatureCollection generated by extract_scouting_zones().
    bin_date : str or pd.Timestamp
        Date of the canonical 14-day bin start.
    bin_index : int
        1-based index of the canonical bin (1..15).
    aoi_bbox : sequence of float
        [min_lon, min_lat, max_lon, max_lat] in EPSG:4326 for regional AOI boundary.
    grid_bbox : sequence of float, optional
        [min_lon, min_lat, max_lon, max_lat] in EPSG:4326 for evaluated diagnostic grid footprint.
    aoi_name : str, default 'Moiben-Soy Agricultural Pilot Zone'
        Name of the target area of interest.
    output_path : str or Path, optional
        Target file path for saving the figure.
    figsize : tuple of int, default (9, 8)
        Figure size in inches.
    dpi : int, default 300
        Resolution for saved raster output.

    Returns
    -------
    matplotlib.figure.Figure
        Rendered figure object.
    """
    fig, ax = plt.subplots(figsize=figsize)

    date_str = str(bin_date)[:10]
    fig.suptitle(
        f"Candidate Scouting Priority Zones — Bin {bin_index} ({date_str})",
        fontsize=13, fontweight="bold", y=0.98
    )
    ax.set_title(
        f"{aoi_name} | Evaluated 503.1 ha Focal Block | Regional Context (CHIRPS 5.5 km, SMAP 9 km)",
        fontsize=8.5, style="italic", color="#444444", pad=14
    )

    min_lon, min_lat, max_lon, max_lat = aoi_bbox

    # 1. Draw Regional Pilot AOI bounding box
    aoi_rect = plt.Rectangle(
        (min_lon, min_lat), max_lon - min_lon, max_lat - min_lat,
        fill=False, edgecolor="#444444", linestyle="--", linewidth=1.2, label="Regional Pilot AOI (490.5 km²)"
    )
    ax.add_patch(aoi_rect)

    # 2. Check for grid_bbox in geojson properties if not explicitly provided
    if grid_bbox is None:
        grid_bbox = geojson_data.get("properties", {}).get("grid_bbox")

    legend_patches = [
        mpatches.Patch(facecolor="none", edgecolor="#444444", linestyle="--", label="Regional Pilot AOI (490.5 km²)")
    ]

    # 3. Draw Evaluated 30 m Diagnostic Footprint
    if grid_bbox is not None and len(grid_bbox) == 4:
        g_min_lon, g_min_lat, g_max_lon, g_max_lat = grid_bbox
        grid_rect = plt.Rectangle(
            (g_min_lon, g_min_lat), g_max_lon - g_min_lon, g_max_lat - g_min_lat,
            facecolor="#e8f0fe", edgecolor="#1a73e8", linestyle="-", linewidth=1.2, alpha=0.45,
            label="Evaluated 30 m Grid (503.1 ha)"
        )
        ax.add_patch(grid_rect)
        legend_patches.append(
            mpatches.Patch(facecolor="#e8f0fe", edgecolor="#1a73e8", linestyle="-", alpha=0.6, label="Evaluated Grid (503.1 ha)")
        )

    features = geojson_data.get("features", [])
    total_area_ha = 0.0

    cases_present = set()

    for feat in features:
        geom = feat.get("geometry")
        props = feat.get("properties", {})
        case_type = props.get("case_type", "UNKNOWN")
        area_ha = float(props.get("area_ha", 0.0))
        total_area_ha += area_ha
        cases_present.add(case_type)

        color = CASE_COLORS.get(case_type, "#e66101")

        if geom:
            sh_geom = shapely_shape(geom)
            if sh_geom.geom_type == "Polygon":
                geoms = [sh_geom]
            elif sh_geom.geom_type == "MultiPolygon":
                geoms = list(sh_geom.geoms)
            else:
                geoms = []

            for g in geoms:
                x, y = g.exterior.xy
                ax.fill(x, y, facecolor=color, alpha=0.75, edgecolor="#222222", linewidth=0.8)

            # Centroid annotation for larger polygons
            c_lat = props.get("centroid_lat")
            c_lon = props.get("centroid_lon")
            if c_lat is not None and c_lon is not None and area_ha >= 5.0:
                ax.plot(c_lon, c_lat, marker="+", color="#111111", markersize=6, mew=1.2)

    # Build legend for cases present
    for c in sorted(cases_present):
        col = CASE_COLORS.get(c, "#888888")
        legend_patches.append(mpatches.Patch(facecolor=col, edgecolor="#222", alpha=0.75, label=f"{c} Candidate Zone"))

    # Set coordinate limits with a small margin
    margin_x = (max_lon - min_lon) * 0.08
    margin_y = (max_lat - min_lat) * 0.08
    ax.set_xlim(min_lon - margin_x, max_lon + margin_x)
    ax.set_ylim(min_lat - margin_y, max_lat + margin_y)

    ax.set_xlabel("Longitude (°E, WGS84 / EPSG:4326)", fontsize=9, fontweight="bold")
    ax.set_ylabel("Latitude (°N, WGS84 / EPSG:4326)", fontsize=9, fontweight="bold")
    ax.grid(True, linestyle=":", alpha=0.6)
    ax.legend(handles=legend_patches, loc="upper right", fontsize=8, framealpha=0.92)

    # Annotation box with summary
    summary_box_text = (
        f"Spatial Evaluation Scope:\n"
        f"• Regional Pilot AOI: 490.5 km² (49,050 ha)\n"
        f"• Evaluated 30 m Footprint: 503.10 ha (5,590 px)\n"
        f"• Actionable Scouting Zones: {len(features)} ({total_area_ha:.2f} ha)\n"
        f"• Minimum Mapping Unit (MMU): >= 2.0 ha"
    )
    ax.text(
        0.03, 0.04, summary_box_text,
        transform=ax.transAxes, fontsize=8, verticalalignment="bottom",
        bbox=dict(boxstyle="round,pad=0.5", facecolor="white", edgecolor="#cccccc", alpha=0.92)
    )

    # Scientific disclaimer footer
    footer = (
        "Scientific Notice: Candidate scouting polygons represent priority screening hypotheses, NOT confirmed crop damage or disease.\n"
        "Regional AOI defines climate/hydrology context; 30 m Sentinel-2 evaluation is conducted over the focal pilot agricultural block."
    )
    fig.text(0.5, 0.01, footer, ha="center", fontsize=7.5, style="italic", color="#555555")

    plt.tight_layout(rect=[0, 0.03, 1, 0.95])

    if output_path is not None:
        p = Path(output_path)
        p.parent.mkdir(parents=True, exist_ok=True)
        fig.savefig(p, dpi=dpi, bbox_inches="tight")

    return fig
