"""Data provenance metadata creation and validation utilities.

Ensures every ingested dataset carries comprehensive origin, version,
licensing, resolution, transformation, and scientific limitation metadata.
"""

from __future__ import annotations

import datetime
from typing import Any, Dict, List, Optional, Union
import xarray as xr


def create_provenance_metadata(
    source_name: str,
    product_name: str,
    product_version: str,
    spatial_resolution: str,
    temporal_resolution: str,
    native_crs: str,
    known_limitations: List[str],
    source_url: Optional[str] = None,
    collection_id: Optional[str] = None,
    transformations_applied: Optional[List[str]] = None,
    extra_attributes: Optional[Dict[str, Any]] = None,
) -> Dict[str, Any]:
    """Create a standardized provenance metadata dictionary.

    Parameters
    ----------
    source_name : str
        Data provider or institution (e.g. 'ANU Centre for Water and Landscape Dynamics / NCI').
    product_name : str
        Official name of the dataset product (e.g. 'Global Root-zone moisture Analysis & Forecasting System').
    product_version : str
        Product version or release identifier (e.g. 'v1.0').
    spatial_resolution : str
        Native spatial resolution description (e.g. '0.1 degree (~10 km)').
    temporal_resolution : str
        Native temporal sampling cadence (e.g. 'Daily').
    native_crs : str
        Native spatial coordinate reference system (e.g. 'EPSG:4326').
    known_limitations : list of str
        Known methodological caveats, missing data causes, or domain constraints.
    source_url : str, optional
        URL or endpoint where the data is hosted.
    collection_id : str, optional
        Catalog collection identifier (e.g. 'sentinel-2-l2a').
    transformations_applied : list of str, optional
        List of transformations applied during ingestion (e.g. ['spatial_crop', 'fill_value_masking']).
    extra_attributes : dict, optional
        Additional custom metadata key-value pairs.

    Returns
    -------
    dict[str, Any]
        Standardized provenance metadata dictionary.
    """
    now_utc = datetime.datetime.now(datetime.timezone.utc).isoformat()
    transformations = transformations_applied if transformations_applied is not None else []

    provenance: Dict[str, Any] = {
        "provenance_source_name": source_name,
        "provenance_product_name": product_name,
        "provenance_product_version": product_version,
        "provenance_access_timestamp_utc": now_utc,
        "provenance_spatial_resolution": spatial_resolution,
        "provenance_temporal_resolution": temporal_resolution,
        "provenance_native_crs": native_crs,
        "provenance_known_limitations": "; ".join(known_limitations),
        "provenance_transformations_applied": "; ".join(transformations) if transformations else "none",
    }

    if source_url:
        provenance["provenance_source_url"] = source_url
    if collection_id:
        provenance["provenance_collection_id"] = collection_id
    if extra_attributes:
        for k, v in extra_attributes.items():
            provenance[f"provenance_{k}"] = str(v)

    return provenance


def attach_provenance(
    ds: Union[xr.Dataset, xr.DataArray],
    provenance_meta: Dict[str, Any],
) -> Union[xr.Dataset, xr.DataArray]:
    """Attach provenance metadata to an xarray Dataset or DataArray attributes.

    Parameters
    ----------
    ds : xr.Dataset or xr.DataArray
        Target xarray data structure.
    provenance_meta : dict
        Provenance metadata dictionary generated by create_provenance_metadata.

    Returns
    -------
    xr.Dataset or xr.DataArray
        The same dataset/dataarray with attached attributes.
    """
    ds.attrs.update(provenance_meta)
    return ds


def validate_provenance(ds: Union[xr.Dataset, xr.DataArray]) -> None:
    """Validate that required provenance fields exist in the dataset attributes.

    Parameters
    ----------
    ds : xr.Dataset or xr.DataArray
        Dataset to check.

    Raises
    ------
    ValueError
        If any mandatory provenance attribute is missing.
    """
    required_fields = [
        "provenance_source_name",
        "provenance_product_name",
        "provenance_product_version",
        "provenance_access_timestamp_utc",
        "provenance_spatial_resolution",
        "provenance_temporal_resolution",
        "provenance_native_crs",
        "provenance_known_limitations",
    ]
    missing = [f for f in required_fields if f not in ds.attrs]
    if missing:
        raise ValueError(
            f"Dataset is missing mandatory provenance attributes: {missing}"
        )
